import type { Conversation } from "@/lib/types";

const telegramPhotoUrl =
  "https://kdwghotfxttlawfttphl.supabase.co/storage/v1/object/public/chat-attachments/telegram/1778756382554_62404a65-54bf-4e7c-86af-b603374f0b64_telegram_photo_84.jpg";
const telegramVoiceUrl =
  "https://kdwghotfxttlawfttphl.supabase.co/storage/v1/object/public/chat-attachments/telegram/1778756510624_d9e9a374-c6c1-4f01-b19f-389e3a9b661c_telegram_voice_88.oga";
const telegramVideoNoteUrl =
  "https://kdwghotfxttlawfttphl.supabase.co/storage/v1/object/public/chat-attachments/telegram/1778756553781_a5ec47b8-1a27-4496-b819-8d8781abd212_telegram_video_note_90.mp4";

export const supportArchivedConversations: Conversation[] = [
  {
    id: "archive_telegram_asadbek",
    backend: "archive",
    name: "Asadbek Davronov",
    label: "TELEGRAM",
    lastMessage: "Dumaloq video yuborildi.",
    time: "16:02",
    unread: 1,
    online: false,
    source: "telegram",
    avatar: telegramPhotoUrl,
    telegramChatId: "7826419001",
    username: "asadbek_davronov",
    lastSeenLabel: "oxirgi suhbat",
    about: [
      "EduLab Academy telegram botidan kelgan suhbat.",
      "Telegram orqali yuborilgan yordam so'rovi.",
    ],
    messages: [
      {
        id: "archive_tg_1",
        author: "student",
        body: "Rasm yuborildi.",
        time: "15:59",
        kind: "image",
        previewUrl: telegramPhotoUrl,
        attachmentUrl: telegramPhotoUrl,
        fileName: "telegram-photo.jpg",
        fileSize: "165 KB",
        read: false,
        createdAt: "2026-05-14T10:59:42.955Z",
      },
      {
        id: "archive_tg_2",
        author: "admin",
        body: "nima bu",
        time: "16:00",
        kind: "text",
        read: true,
        createdAt: "2026-05-14T11:00:00.000Z",
      },
      {
        id: "archive_tg_3",
        author: "student",
        body: "Ovozli xabar yuborildi.",
        time: "16:01",
        kind: "voice",
        duration: "0:12",
        fileName: "telegram-voice.oga",
        fileSize: "63 KB",
        attachmentUrl: telegramVoiceUrl,
        read: false,
        createdAt: "2026-05-14T11:01:50.795Z",
      },
      {
        id: "archive_tg_4",
        author: "student",
        body: "Dumaloq video yuborildi.",
        time: "16:02",
        kind: "round_video",
        fileName: "telegram-video-note.mp4",
        fileSize: "0.3 MB",
        attachmentUrl: telegramVideoNoteUrl,
        read: false,
        createdAt: "2026-05-14T11:02:34.590Z",
      },
    ],
  },
  {
    id: "archive_telegram_lab",
    backend: "archive",
    name: "Laboratoriya",
    label: "TELEGRAM",
    lastMessage: "Dumaloq video yuborildi.",
    time: "18:21",
    unread: 0,
    online: false,
    source: "telegram",
    telegramChatId: "7826419002",
    lastSeenLabel: "oxirgi suhbat",
    about: ["Telegram orqali kelgan laboratoriya bo'yicha murojaat."],
    messages: [
      {
        id: "archive_lab_1",
        author: "student",
        body: "Laboratoriya ishi haqida ma'lumot berasizmi?",
        time: "18:21",
        kind: "text",
        read: true,
        createdAt: "2026-05-14T13:21:00.000Z",
      },
      {
        id: "archive_lab_2",
        author: "admin",
        body: "Albatta, qaysi modul bo'yicha yordam kerak?",
        time: "18:22",
        kind: "text",
        read: true,
        createdAt: "2026-05-14T13:22:00.000Z",
      },
    ],
  },
  {
    id: "archive_app_asadbek",
    backend: "archive",
    name: "Asadbek Davronov",
    label: "APK",
    lastMessage: "Student ilovasidan savol yuborildi.",
    time: "17:45",
    unread: 1,
    online: true,
    source: "student_app",
    participantUserId: "app-user-asadbek",
    phone: "+998 33 686 20 01",
    lastSeenLabel: "hozir faol",
    about: ["Student APK orqali kelgan murojaat.", "Profil rasmi mavjud bo'lsa APK profilidan olinadi."],
    messages: [
      {
        id: "archive_app_1",
        author: "student",
        body: "Darsdagi test javoblari saqlanmayapti.",
        time: "17:43",
        kind: "text",
        read: false,
        createdAt: "2026-05-14T12:43:00.000Z",
      },
      {
        id: "archive_app_2",
        author: "admin",
        body: "Telefoningizda internetni tekshirib, qayta urinib ko'ring.",
        time: "17:45",
        kind: "text",
        read: true,
        createdAt: "2026-05-14T12:45:00.000Z",
      },
    ],
  },
];
