enum AppLanguage { uzLatin, ru, uzCyrillic }

extension AppLanguageX on AppLanguage {
  String get storageValue {
    switch (this) {
      case AppLanguage.uzLatin:
        return 'uz_latin';
      case AppLanguage.ru:
        return 'ru';
      case AppLanguage.uzCyrillic:
        return 'uz_cyrillic';
    }
  }

  String get label {
    switch (this) {
      case AppLanguage.uzLatin:
        return 'O‘zbek';
      case AppLanguage.ru:
        return 'Русский';
      case AppLanguage.uzCyrillic:
        return 'Ўзбекча';
    }
  }

  String get shortLabel {
    switch (this) {
      case AppLanguage.uzLatin:
        return 'UZ';
      case AppLanguage.ru:
        return 'RU';
      case AppLanguage.uzCyrillic:
        return 'ЎЗ';
    }
  }

  static AppLanguage fromStorageValue(String? value) {
    switch (value) {
      case 'uz_latin':
        return AppLanguage.uzLatin;
      case 'ru':
        return AppLanguage.ru;
      case 'uz_cyrillic':
        return AppLanguage.uzCyrillic;
      default:
        return AppLanguage.uzLatin;
    }
  }
}

String languageOptionDescription(
  AppLanguage currentLanguage,
  AppLanguage option,
) {
  return _languageOptionDescriptions[currentLanguage]?[option] ??
      _languageOptionDescriptions[AppLanguage.uzLatin]![option]!;
}

String studentText(AppLanguage language, String key) {
  return _studentTexts[language]?[key] ??
      _studentTexts[AppLanguage.uzLatin]![key] ??
      key;
}

const _languageOptionDescriptions = {
  AppLanguage.uzLatin: {
    AppLanguage.uzLatin: 'Lotin yozuvida o‘zbekcha interfeys',
    AppLanguage.ru: 'Rus tilidagi interfeys',
    AppLanguage.uzCyrillic: 'Kiril yozuvida o‘zbekcha interfeys',
  },
  AppLanguage.ru: {
    AppLanguage.uzLatin: 'Интерфейс на узбекском (латиница)',
    AppLanguage.ru: 'Интерфейс на русском языке',
    AppLanguage.uzCyrillic: 'Интерфейс на узбекском (кириллица)',
  },
  AppLanguage.uzCyrillic: {
    AppLanguage.uzLatin: 'Ўзбекча интерфейс (лотин ёзуви)',
    AppLanguage.ru: 'Рус тилидаги интерфейс',
    AppLanguage.uzCyrillic: 'Ўзбекча интерфейс (кирилл ёзуви)',
  },
};

const _studentTexts = {
  AppLanguage.uzLatin: {
    'loading': 'Laboratoriya ta’limi yuklanmoqda',
    'welcome': 'Xush kelibsiz',
    'signin_hint': 'Telefon raqamingiz va parolingiz bilan davom eting.',
    'create_account': 'Ro‘yxatdan o‘tish',
    'sign_in_desc': 'Akkauntingizga kirish',
    'create_account_desc': 'Professional o‘rganishni boshlang',
    'telegram_onboarding_note': 'Ro‘yxatdan o‘tish jarayonida Telegram orqali akkauntingiz tasdiqlanadi.',
    'topic_not_found': 'Mavzu topilmadi',
    'no_active_topic_in_module': 'Bu modulda hali ochiq mavzu yo‘q.',
    'back_to_module': 'Modulga qaytish',
    'module_not_found': 'Modul topilmadi',
    'no_modules_assigned': 'Hali sizga modul biriktirilmagan.',
    'refresh': 'Yangilash',
    'quiz_not_added': 'Test hali qo‘shilmagan',
    'quiz_not_added_desc': 'Admin panel orqali bu mavzuga real savollar qo‘shilganda test ochiladi.',
    'back_to_topic': 'Mavzuga qaytish',
    'pdf_not_set': 'Bu mavzu uchun PDF fayl linki hali belgilanmagan.',
    'final_quiz_not_ready': 'Yakuniy imtihon hali tayyor emas',
    'final_quiz_not_ready_desc': 'Modul savollari admin panelda qo‘shilgandan keyin yakuniy imtihon ochiladi.',
    'register_hint': 'Ism familiya, telefon raqam va parol kiriting.',
    'full_name': 'Ism familiya',
    'admin_login_label': 'Login',
    'admin_login_hint': 'Admin login va parol bilan kiring.',
    'phone': 'Telefon raqam',
    'password': 'Parol',
    'show_password': 'Parolni ko‘rsatish',
    'hide_password': 'Parolni yashirish',
    'forgot': 'Parolni unutdingizmi?',
    'forgot_hint':
        'Telefon raqam, yangi parol va Telegram kodi orqali parolni yangilang.',
    'reset_password': 'Parolni tiklash',
    'reset_password_hint':
        'Telefon raqamingizni kiriting, yangi parolni ikki marta yozing va Telegram orqali tasdiqlang.',
    'new_password': 'Yangi parol',
    'register_subtitle': 'Kelajakdagi laboratoriya mutaxassislari safiga qo‘shiling.',
    'login_subtitle': 'O‘quv safaringizni davom ettiring va natijangizni oshiring.',
    'your_info': 'Ma’lumotlaringiz',
    'login_title': 'Hisobga kirish',
    'security': 'Xavfsizlik',
    'secure_title': 'Xavfsiz va ishonchli',
    'secure_desc': 'Ma’lumotlaringiz himoyalangan va xavfsiz saqlanadi.',
    'step_info': 'Ma’lumotlar',
    'step_verify': 'Tasdiqlash',
    'step_complete': 'Tugatish',
    'create_password': 'Parol yarating',
    'enter_password': 'Parolingizni kiriting',
    'reenter_password': 'Parolni qayta kiriting',
    'remember_me': 'Eslab qolish',
    'telegram_verify_note': 'Hisobni tasdiqlash uchun Telegram bot orqali kod olasiz.',
    'verification_code': 'Tasdiqlash kodi',
    '4_digit_code': '4 xonali kod',
    'get_telegram_code': 'Telegram kod olish',
    'have_account': 'Hisobingiz bormi?',
    'no_account': 'Hisobingiz yo‘qmi?',
    'terms_agreement': 'Kirish orqali siz xizmat shartlari va maxfiylik siyosatiga rozilik bildirasiz.',
    'keep_learning_growing': 'O‘rganishda davom eting,\nO‘sishda davom eting! 🚀',
    'journey_starts': 'Sizning bilim yo\'lingiz shu yerdan boshlanadi.',
    'see_all': 'Barchasini ko‘rish >',
    'recent_activity': 'So‘nggi faollik',
    'your_statistics': 'Statistikangiz',
    'stat_courses': 'O’rganilgan kurslar',
    'stat_average': 'O’rtacha natija',
    'stat_streak': 'Ketma-ket kun',
    'stat_achievements': 'Yutuqlar',
    'latest_activity': 'Sizning so‘nggi o‘quv faolligingiz',
    'quick_access': 'Tezkor kirish',
    'courses': 'Kurslar',
    'my_progress': 'Mening natijam',
    'quizzes': 'Viktorinalar',
    'bookmarks': 'Xatcho‘plar',
    'onboarding_slide1_title': 'Klinik laboratoriya\nSohasini <purple>o‘rganing</purple>',
    'onboarding_slide1_subtitle': 'Gematologiya, mikrobiologiya, bioximiya va boshqalarni mutaxassislar kurslari orqali o‘zlashtiring.',
    'onboarding_slide2_title': 'Interaktiv\n<purple>Tibbiy darslar</purple>',
    'onboarding_slide2_subtitle': 'O‘rganishni samarali va maroqli qiluvchi qiziqarli video darslar, viktorinalar va manbalar.',
    'onboarding_slide3_title': 'Sertifikat oling va\nNatijani <purple>kuzating</purple>',
    'onboarding_slide3_subtitle': 'Sertifikatga ega bo‘ling, natijangizni kuzatib boring va o‘quv maqsadlaringizga erishing.',
    'onboarding_skip': 'O‘tkazib yuborish',
    'onboarding_get_started': 'Boshlash',
    'onboarding_welcome': '<purple>LabProof</purple> Academy\'ga\nXush kelibsiz',
    'onboarding_journey': 'Laboratoriya mutaxassisi bo‘lish yo‘lidagi sayohatingiz shu yerdan boshlanadi.',
    'onboarding_access_account': 'Hisobingizga kiring',
    'onboarding_start_journey': 'O‘quv sayohatingizni boshlang',
    'welcome_to': 'LabProof Academy ga xush kelibsiz',
    'admin_login_subtitle': 'LabProof Academy admin paneliga kirish',
    'confirm_password': 'Parolni tasdiqlang',
    'passwords_not_match': 'Parollar bir xil emas.',
    'reset_success':
        'Parol yangilandi. Endi yangi parol bilan kirishingiz mumkin.',
    'full_name_required': 'Ism familiyani kiriting.',
    'phone_invalid': 'Telefon raqam +998 dan keyin 9 ta raqam bo‘lishi kerak.',
    'password_required': 'Parol kiriting.',
    'password_min': 'Parol kamida 6 ta belgi bo‘lishi kerak.',
    'login': 'Kirish',
    'register': 'Ro‘yxatdan o‘tish',
    'verify': 'Tasdiqlash',
    'get_code': 'Kodni olish',
    'open_bot_again': 'Telegram botni qayta ochish',
    'code': 'Telegram kodi',
    'code_hint': 'Bot bergan kodni kiriting',
    'telegram_hint':
        'Telegram bot avval ism familiyani tekshiradi, keyin raqamni tugma orqali qabul qiladi.',
    'telegram_opened':
        'Telegram ochildi. Botdagi “📞 Raqamni yuborish” tugmasini bosing, keyin kodni shu yerga kiriting.',
    'already': 'Avval ro‘yxatdan o‘tganmisiz?',
    'new': 'Yangi foydalanuvchimisiz?',
    'student': 'Student',
    'admin': 'Admin',
    'home': 'Bosh sahifa',
    'modules': 'Modullar',
    'results': 'Natijalar',
    'progress': 'Progress',
    'profile': 'Profil',
    'hello': 'Salom',
    'today': 'Bugun o‘qish oqimini davom ettiring.',
    'continue': 'Davom etish',
    'continue_learning': 'O‘qishni davom ettirish',
    'settings': 'Sozlamalar',
    'language': 'Til',
    'language_picker_hint': 'Ilova tilini qulay ko‘rinishda tanlang.',
    'dark_mode': 'Qorong‘i rejim',
    'logout': 'Chiqish',
    'profile_subtitle': 'Shaxsiy ma’lumotlar, til va bildirishnoma boshqaruvi',
    'edit_profile': 'Profilni tahrirlash',
    'phone_not_set': 'Telefon raqam yo‘q',
    'address_not_set': 'Manzil kiritilmagan',
    'male': 'Erkak',
    'female': 'Ayol',
    'age_suffix': 'yosh',
    'studying_modules': 'O‘rganayotgan modullar',
    'completed_modules': 'Tugatilgan modullar',
    'overall_score': 'Umumiy natija',
    'notifications': 'Bildirishnomalar',
    'notifications_enabled_hint': 'Yoqilgan, yangi e’lonlar keladi',
    'notifications_disabled_hint': 'O‘chiq, xabarlar oqimi to‘xtatilgan',
    'contact_admin': 'LabProof Academy Yordam',
    'contact_admin_subtitle': 'Savol, muammo yoki taklif yuboring',
    'support_subject': 'Xabar mavzusi',
    'support_message': 'Xabar matni',
    'support_message_hint': 'Muammo yoki savolingizni qisqacha yozing...',
    'fill_subject_message': 'Mavzu va xabar matnini to‘ldiring.',
    'send_message': 'Xabar yuborish',
    'message_sent': 'Xabaringiz adminga yuborildi.',
    'dark_mode_enabled': 'Qorong‘i ko‘rinish faollashgan',
    'light_mode_enabled': 'Yorug‘ ko‘rinish ishlatilmoqda',
    'check_updates': 'Yangilanishni tekshirish',
    'check_updates_subtitle':
        'So‘nggi release va APK yangilanishini tekshirish',
    'close_session': 'Joriy sessiyani yopish',
    'version_label': 'Versiya',
    'notifications_title': 'Bildirishnomalar',
    'new_messages_count_suffix': 'ta yangi xabar',
    'notifications_disabled_profile':
        'Bildirishnomalar profildan o‘chirib qo‘yilgan',
    'mark_all_read': 'Barchasi o‘qildi',
    'notifications_empty_title': 'Xabarlar hali yo‘q',
    'notifications_empty_message':
        'Admin paneldan yuborilgan yangilik va e’lonlar shu yerda ko‘rinadi.',
    'notifications_off_title': 'Bildirishnomalar o‘chiq',
    'notifications_off_message':
        'Profil sahifasidagi switch yoqilganda admin yuborgan yangiliklar shu yerga tushadi.',
    'just_now': 'Hozirgina',
    'minutes_ago': 'daqiqa oldin',
    'hours_ago': 'soat oldin',
    'days_ago': 'kun oldin',
    'profile_edit_title': 'Profilni tahrirlash',
    'profile_edit_subtitle':
        'Shaxsiy ma’lumotlar, manzil va profil rasmini yangilang.',
    'upload_profile_photo': 'Profil rasmini yuklash',
    'first_name': 'Ism',
    'last_name': 'Familiya',
    'gender': 'Jins',
    'choose': 'Tanlang',
    'region': 'Viloyat',
    'district': 'Tuman',
    'mahalla': 'Mahalla',
    'street_house': 'Ko‘cha / uy',
    'saving': 'Saqlanmoqda...',
    'save': 'Saqlash',
    'choose_gender': 'Jinsni tanlang',
    'choose_region': 'Viloyatni tanlang',
    'choose_district': 'Tumanni tanlang',
    'select_region_first': 'Avval viloyatni tanlang.',
    'name_complete_error': 'Ism va familiyani to‘liq kiriting.',
    'choose_gender_error': 'Jinsni tanlang.',
    'choose_region_district_error': 'Viloyat va tumanni tanlang.',
    'age_range_error': 'Yosh 10 dan 120 gacha bo‘lishi kerak.',
    'profile_updated': 'Profil ma’lumotlari yangilandi.',
    'active_modules': 'Faol modullar',
    'active_modules_subtitle': 'Ochilgan va davom etayotgan bloklar',
    'score_average_subtitle': 'Quiz va final testlar o‘rtachasi',
    'completed_topics': 'Tugatilgan mavzu',
    'completed_topics_subtitle': 'Bosqichma-bosqich bajarilgan darslar',
    'certificates_subtitle': 'Yakunlangan modullardan beriladi',
    'average_result': 'O‘rtacha natija',
    'evaluated_topics': 'Baholangan mavzular',
    'notifications_tooltip': 'Bildirishnomalar',
    'modules_subtitle': 'Modullar ketma-ket ochiladi va progress saqlanadi',
    'open': 'Ochiq',
    'locked': 'Yopiq',
    'topics': 'Mavzular',
    'pass_rule': '70% o‘tish sharti',
    'final_exam': 'Modul yakuniy testi',
    'pdf_lesson': '1. PDF / Matn darsi',
    'video_lesson': '2. Video dars',
    'topic_quiz': '3. Mavzu testi',
    'finish_reading': 'O‘qishni tugatdim',
    'finish_video': 'Videoni tugatdim',
    'question': 'Savol',
    'previous': 'Oldingi',
    'next': 'Keyingi',
    'submit': 'Topshirish',
    'great': 'Ajoyib!',
    'topic_done': 'mavzusini tugatdingiz.',
    'back_topics': 'Mavzular ro‘yxatiga qaytish',
    'start_test': 'Testni boshlash',
    'see_result': 'Natijani ko‘rish',
    'passed': 'O‘tdingiz!',
    'failed': 'O‘ta olmadingiz',
    'next_module': 'Keyingi modul ochildi',
    'review_retake': 'Darslarni qayta ko‘rib, testni qayta topshiring',
    'restudy': 'Qayta o‘qish',
    'go_module_2': '2-modulga o‘tish',
    'analytics': 'Test tahlillari',
    'certificate': 'Sertifikat',
    'achievements': 'Yutuqlar',
    'description': 'Tavsif',
    'main_formula': 'Asosiy formula',
    'video_not_open': 'Videoni ochib bo‘lmadi.',
    'playback_speed': 'Ijro tezligi',
    'open_external_video': 'Tashqi videoni ochish',
    'send_question': 'Savol yuborish',
    'join': 'Qo‘shilish',
    'send_text_or_attachment': 'Hech bo‘lmasa matn yoki biriktirma yuboring.',
    'stop': 'To‘xtatish',
    'video_not_set': 'Bu mavzu uchun video havola hali belgilanmagan.',
    'video_external_hint': 'Video havola orqali ochiladi. YouTube havolasi bo‘lsa, video ilova ichida ko‘rsatiladi.',
    'video_inapp_hint': 'YouTube video ilova ichida ko‘rsatilmoqda.',
  },
  AppLanguage.ru: {
    'loading': 'Загрузка лабораторного обучения',
    'welcome': 'Добро пожаловать',
    'signin_hint': 'Продолжайте с номером телефона и паролем.',
    'create_account': 'Регистрация',
    'sign_in_desc': 'Войти в свой аккаунт',
    'create_account_desc': 'Начните профессиональное обучение',
    'telegram_onboarding_note': 'В процессе регистрации ваш аккаунт будет подтвержден через Telegram.',
    'topic_not_found': 'Тема не найдена',
    'no_active_topic_in_module': 'В этом модуле пока нет открытых тем.',
    'back_to_module': 'Вернуться в модуль',
    'module_not_found': 'Модуль не найден',
    'no_modules_assigned': 'Вам еще не назначены модули.',
    'refresh': 'Обновить',
    'quiz_not_added': 'Тест еще не добавлен',
    'quiz_not_added_desc': 'Тест откроется, когда через админ-панель будут добавлены реальные вопросы.',
    'back_to_topic': 'Вернуться к теме',
    'pdf_not_set': 'PDF-ссылка для этой темы еще не установлена.',
    'final_quiz_not_ready': 'Итоговый экзамен еще не готов',
    'final_quiz_not_ready_desc': 'Итоговый экзамен откроется после того, как вопросы модуля будут добавлены в админ-панели.',
    'register_hint': 'Введите имя, телефон и пароль.',
    'full_name': 'Имя и фамилия',
    'admin_login_label': 'Логин',
    'admin_login_hint': 'Войдите с логином администратора и паролем.',
    'phone': 'Номер телефона',
    'password': 'Пароль',
    'show_password': 'Показать пароль',
    'hide_password': 'Скрыть пароль',
    'forgot': 'Забыли пароль?',
    'forgot_hint':
        'Обновите пароль через номер телефона, новый пароль и код из Telegram.',
    'reset_password': 'Сброс пароля',
    'reset_password_hint':
        'Введите номер телефона, дважды укажите новый пароль и подтвердите его через Telegram.',
    'new_password': 'Новый пароль',
    'register_subtitle': 'Присоединяйтесь к будущим специалистам лаборатории.',
    'login_subtitle': 'Продолжайте свой учебный путь и улучшайте результаты.',
    'your_info': 'Ваши данные',
    'login_title': 'Вход в аккаунт',
    'security': 'Безопасность',
    'secure_title': 'Безопасно и надежно',
    'secure_desc': 'Ваши данные защищены и хранятся в безопасности.',
    'step_info': 'Данные',
    'step_verify': 'Проверка',
    'step_complete': 'Готово',
    'create_password': 'Создайте пароль',
    'enter_password': 'Введите пароль',
    'reenter_password': 'Введите пароль еще раз',
    'remember_me': 'Запомнить меня',
    'telegram_verify_note': 'Для подтверждения аккаунта вы получите код через Telegram бота.',
    'verification_code': 'Код подтверждения',
    '4_digit_code': '4-значный код',
    'get_telegram_code': 'Получить код Telegram',
    'have_account': 'Уже есть аккаунт?',
    'no_account': 'Нет аккаунта?',
    'terms_agreement': 'Входя в систему, вы соглашаетесь с условиями обслуживания и политикой конфиденциальности.',
    'keep_learning_growing': 'Продолжайте учиться,\nПродолжайте расти! 🚀',
    'journey_starts': 'Ваше путешествие начинается здесь.',
    'see_all': 'Посмотреть все >',
    'recent_activity': 'Недавняя активность',
    'your_statistics': 'Ваша статистика',
    'stat_courses': 'Изучено курсов',
    'stat_average': 'Средний результат',
    'stat_streak': 'Ударный режим',
    'stat_achievements': 'Достижения',
    'latest_activity': 'Ваша последняя учебная активность',
    'quick_access': 'Быстрый доступ',
    'courses': 'Курсы',
    'my_progress': 'Мой прогресс',
    'quizzes': 'Тесты',
    'bookmarks': 'Закладки',
    'onboarding_slide1_title': 'Изучайте клиническую\nЛабораторную <purple>науку</purple>',
    'onboarding_slide1_subtitle': 'Освойте гематологию, микробиологию, биохимию и многое другое с курсами от экспертов.',
    'onboarding_slide2_title': 'Интерактивные\n<purple>Медицинские уроки</purple>',
    'onboarding_slide2_subtitle': 'Увлекательные видеоуроки, викторины и ресурсы для эффективного и приятного обучения.',
    'onboarding_slide3_title': 'Получайте сертификаты\nИ следите за <purple>успехом</purple>',
    'onboarding_slide3_subtitle': 'Сертифицируйтесь, отслеживайте прогресс и достигайте своих учебных целей шаг за шагом.',
    'onboarding_skip': 'Пропустить',
    'onboarding_get_started': 'Начать',
    'onboarding_welcome': 'Добро пожаловать в\n<purple>LabProof</purple> Academy',
    'onboarding_journey': 'Ваш путь к тому, чтобы стать специалистом лаборатории, начинается здесь.',
    'onboarding_access_account': 'Войдите в аккаунт',
    'onboarding_start_journey': 'Начните свое обучение',
    'welcome_to': 'Добро пожаловать в LabProof Academy',
    'admin_login_subtitle': 'Вход в панель администратора LabProof Academy',
    'confirm_password': 'Подтвердите пароль',
    'passwords_not_match': 'Пароли не совпадают.',
    'reset_success': 'Пароль обновлен. Теперь можно войти с новым паролем.',
    'full_name_required': 'Введите имя и фамилию.',
    'phone_invalid': 'После +998 должно быть 9 цифр номера телефона.',
    'password_required': 'Введите пароль.',
    'password_min': 'Пароль должен быть не менее 6 символов.',
    'login': 'Войти',
    'register': 'Зарегистрироваться',
    'verify': 'Подтвердить',
    'get_code': 'Получить код',
    'open_bot_again': 'Открыть Telegram-бота снова',
    'code': 'Код из Telegram',
    'code_hint': 'Введите код от бота',
    'telegram_hint':
        'Telegram-бот сначала проверит имя и фамилию, затем примет номер только через кнопку.',
    'telegram_opened':
        'Telegram открыт. Нажмите у бота кнопку отправки номера, затем введите код здесь.',
    'already': 'Уже зарегистрированы?',
    'new': 'Новый пользователь?',
    'student': 'Студент',
    'admin': 'Админ',
    'home': 'Главная',
    'modules': 'Модули',
    'results': 'Результаты',
    'progress': 'Прогресс',
    'profile': 'Профиль',
    'hello': 'Здравствуйте',
    'today': 'Сегодня продолжайте обучение.',
    'continue': 'Продолжить',
    'continue_learning': 'Продолжить обучение',
    'settings': 'Настройки',
    'language': 'Язык',
    'language_picker_hint': 'Выберите удобный язык интерфейса.',
    'dark_mode': 'Темный режим',
    'logout': 'Выйти',
    'profile_subtitle': 'Личные данные, язык и управление уведомлениями',
    'edit_profile': 'Редактировать профиль',
    'phone_not_set': 'Номер телефона не указан',
    'address_not_set': 'Адрес не указан',
    'male': 'Мужской',
    'female': 'Женский',
    'age_suffix': 'лет',
    'studying_modules': 'Изучаемые модули',
    'completed_modules': 'Завершенные модули',
    'overall_score': 'Общий результат',
    'notifications': 'Уведомления',
    'notifications_enabled_hint': 'Включены, новые объявления будут приходить',
    'notifications_disabled_hint': 'Выключены, поток уведомлений остановлен',
    'contact_admin': 'Поддержка LabProof Academy',
    'contact_admin_subtitle': 'Отправьте вопрос, проблему или предложение',
    'support_subject': 'Тема сообщения',
    'support_message': 'Текст сообщения',
    'support_message_hint': 'Кратко опишите вопрос или проблему...',
    'fill_subject_message': 'Заполните тему и текст сообщения.',
    'send_message': 'Отправить сообщение',
    'message_sent': 'Сообщение отправлено администратору.',
    'dark_mode_enabled': 'Темная тема включена',
    'light_mode_enabled': 'Используется светлая тема',
    'check_updates': 'Проверить обновления',
    'check_updates_subtitle': 'Проверить последний релиз и обновление APK',
    'close_session': 'Завершить текущую сессию',
    'version_label': 'Версия',
    'notifications_title': 'Уведомления',
    'new_messages_count_suffix': 'новых сообщений',
    'notifications_disabled_profile': 'Уведомления отключены в разделе профиля',
    'mark_all_read': 'Прочитать все',
    'notifications_empty_title': 'Сообщений пока нет',
    'notifications_empty_message':
        'Новости и объявления, отправленные из админ-панели, появятся здесь.',
    'notifications_off_title': 'Уведомления выключены',
    'notifications_off_message':
        'Когда переключатель в профиле включен, новости от администратора появятся здесь.',
    'just_now': 'Только что',
    'minutes_ago': 'минут назад',
    'hours_ago': 'часов назад',
    'days_ago': 'дней назад',
    'profile_edit_title': 'Редактировать профиль',
    'profile_edit_subtitle': 'Обновите личные данные, адрес и фото профиля.',
    'upload_profile_photo': 'Загрузить фото профиля',
    'first_name': 'Имя',
    'last_name': 'Фамилия',
    'gender': 'Пол',
    'choose': 'Выберите',
    'region': 'Область',
    'district': 'Район',
    'mahalla': 'Махалля',
    'street_house': 'Улица / дом',
    'saving': 'Сохранение...',
    'save': 'Сохранить',
    'choose_gender': 'Выберите пол',
    'choose_region': 'Выберите область',
    'choose_district': 'Выберите район',
    'select_region_first': 'Сначала выберите область.',
    'name_complete_error': 'Введите имя и фамилию полностью.',
    'choose_gender_error': 'Выберите пол.',
    'choose_region_district_error': 'Выберите область и район.',
    'age_range_error': 'Возраст должен быть от 10 до 120 лет.',
    'profile_updated': 'Данные профиля обновлены.',
    'active_modules': 'Активные модули',
    'active_modules_subtitle': 'Открытые и продолжающиеся блоки',
    'score_average_subtitle': 'Средний балл по квизам и финальным тестам',
    'completed_topics': 'Завершенные темы',
    'completed_topics_subtitle': 'Уроки, пройденные по шагам',
    'certificates_subtitle': 'Выдаются за завершенные модули',
    'average_result': 'Средний результат',
    'evaluated_topics': 'Оцененные темы',
    'notifications_tooltip': 'Уведомления',
    'modules_subtitle':
        'Модули открываются последовательно, прогресс сохраняется',
    'open': 'Открыт',
    'locked': 'Закрыт',
    'topics': 'Темы',
    'pass_rule': 'Проходной балл 70%',
    'final_exam': 'Итоговый тест модуля',
    'pdf_lesson': '1. PDF / Текстовый урок',
    'video_lesson': '2. Видео урок',
    'topic_quiz': '3. Тест темы',
    'finish_reading': 'Я прочитал',
    'finish_video': 'Я посмотрел видео',
    'question': 'Вопрос',
    'previous': 'Назад',
    'next': 'Далее',
    'submit': 'Сдать',
    'great': 'Отлично!',
    'topic_done': 'тема завершена.',
    'back_topics': 'Вернуться к списку тем',
    'start_test': 'Начать тест',
    'see_result': 'Посмотреть результат',
    'passed': 'Вы прошли!',
    'failed': 'Вы не прошли',
    'next_module': 'Следующий модуль открыт',
    'review_retake': 'Повторите уроки и пересдайте тест',
    'restudy': 'Повторить',
    'go_module_2': 'Перейти ко 2-модулю',
    'analytics': 'Аналитика тестов',
    'certificate': 'Сертификат',
    'achievements': 'Достижения',
    'description': 'Описание',
    'main_formula': 'Основная формула',
    'video_not_open': 'Не удалось открыть видео.',
    'playback_speed': 'Скорость воспроизведения',
    'open_external_video': 'Открыть внешнее видео',
    'send_question': 'Отправить вопрос',
    'join': 'Присоединиться',
    'send_text_or_attachment': 'Пожалуйста, отправьте хотя бы текст или вложение.',
    'stop': 'Остановить',
    'video_not_set': 'Видео ссылка для этой темы еще не установлена.',
    'video_external_hint': 'Видео откроется по ссылке. Если есть ссылка на YouTube, видео будет показано внутри приложения.',
    'video_inapp_hint': 'Видео YouTube воспроизводится внутри приложения.',
  },
  AppLanguage.uzCyrillic: {
    'loading': 'Лаборатория таълими юкланмоқда',
    'signin_hint': 'Телефон рақамингиз ва паролингиз билан давом этинг.',
    'create_account': 'Рўйхатдан ўтиш',
    'sign_in_desc': 'Аккаунтингизга кириш',
    'create_account_desc': 'Профессионал ўрганишни бошланг',
    'telegram_onboarding_note': 'Рўйхатдан ўтиш жараёнида Telegram орқали аккаунтингиз тасдиқланади.',
    'topic_not_found': 'Мавзу топилмади',
    'no_active_topic_in_module': 'Бу модулда ҳали очиқ мавзу йўқ.',
    'back_to_module': 'Модулга қайтиш',
    'module_not_found': 'Модул топилмади',
    'no_modules_assigned': 'Ҳали сизга модул бириктирилмаган.',
    'refresh': 'Янгилаш',
    'quiz_not_added': 'Тест ҳали қўшилмаган',
    'quiz_not_added_desc': 'Админ панель орқали бу мавзуга реал саволлар қўшилганда тест очилади.',
    'back_to_topic': 'Мавзуга қайтиш',
    'pdf_not_set': 'Бу мавзу учун PDF файл линки ҳали белгиланмаган.',
    'final_quiz_not_ready': 'Якуний имтиҳон ҳали тайёр эмас',
    'final_quiz_not_ready_desc': 'Модул саволлари админ панелда қўшилгандан кейин якуний имтиҳон очилади.',
    'register_hint': 'Исм фамилия, телефон рақам ва парол киритинг.',
    'full_name': 'Исм фамилия',
    'admin_login_label': 'Логин',
    'admin_login_hint': 'Админ логин ва парол билан киринг.',
    'phone': 'Телефон рақам',
    'password': 'Парол',
    'show_password': 'Паролни кўрсатиш',
    'hide_password': 'Паролни яшириш',
    'forgot': 'Паролни унутдингизми?',
    'forgot_hint':
        'Телефон рақам, янги парол ва Telegram коди орқали паролни янгиланг.',
    'reset_password': 'Паролни тиклаш',
    'reset_password_hint':
        'Телефон рақамингизни киритинг, янги паролни икки марта ёзинг ва Telegram орқали тасдиқланг.',
    'new_password': 'Янги парол',
    'register_subtitle': 'Келажакдаги лаборатория мутахассислари сафига қўшилинг.',
    'login_subtitle': 'Ўқув сафарингизни давом эттиринг ва натижангизни оширинг.',
    'your_info': 'Маълумотларингиз',
    'login_title': 'Ҳисобга кириш',
    'security': 'Хавфсизлик',
    'secure_title': 'Хавфсиз ва ишончли',
    'secure_desc': 'Маълумотларингиз ҳимояланган ва хавфсиз сақланади.',
    'step_info': 'Маълумотлар',
    'step_verify': 'Тасдиқлаш',
    'step_complete': 'Тугатиш',
    'create_password': 'Парол яратинг',
    'enter_password': 'Паролингизни киритинг',
    'reenter_password': 'Паролни қайта киритинг',
    'remember_me': 'Эслаб қолиш',
    'telegram_verify_note': 'Ҳисобни тасдиқлаш учун Telegram бот орқали код оласиз.',
    'verification_code': 'Тасдиқлаш коди',
    '4_digit_code': '4 хонали код',
    'get_telegram_code': 'Telegram код олиш',
    'have_account': 'Ҳисобингиз борми?',
    'no_account': 'Ҳисобингиз йўқми?',
    'terms_agreement': 'Кириш орқали сиз хизмат шартлари ва махфийлик сиёсатига розилик билдирасиз.',
    'keep_learning_growing': 'Ўрганишда давом этинг,\nЎсишда давом этинг! 🚀',
    'journey_starts': 'Сизнинг билим йўлингиз шу ердан бошланади.',
    'see_all': 'Барчасини кўриш >',
    'recent_activity': 'Сўнгги faollik',
    'your_statistics': 'Статистикангиз',
    'stat_courses': 'Ўрганилган курслар',
    'stat_average': 'Ўртача натижа',
    'stat_streak': 'Кетма-кет кун',
    'stat_achievements': 'Ютуқлар',
    'latest_activity': 'Сизнинг сўнгги ўқув фаоллигингиз',
    'quick_access': 'Тезкор кириш',
    'courses': 'Курслар',
    'my_progress': 'Менинг натижам',
    'quizzes': 'Викториналар',
    'bookmarks': 'Хатчўплар',
    'onboarding_slide1_title': 'Клиник лаборатория\nСоҳасини <purple>ўрганинг</purple>',
    'onboarding_slide1_subtitle': 'Гематология, микробиология, биохимия ва бошқаларни мутахассислар курслари орқали ўзлаштиринг.',
    'onboarding_slide2_title': 'Интерактив\n<purple>Тиббий дарслар</purple>',
    'onboarding_slide2_subtitle': 'Ўрганишни самарали ва мароқли қилувчи қизиқарли видео дарслар, викториналар ва манбалар.',
    'onboarding_slide3_title': 'Сертификат олинг ва\nНатижани <purple>кузатинг</purple>',
    'onboarding_slide3_subtitle': 'Сертификатга эга бўлинг, натижангизни кузатиб боринг ва ўқув мақсадларингизга эришинг.',
    'onboarding_skip': 'Ўтказиб юбориш',
    'onboarding_get_started': 'Бошлаш',
    'onboarding_welcome': '<purple>LabProof</purple> Academy\'ga\nХуш келибсиз',
    'onboarding_journey': 'Лаборатория мутахассиси бўлиш йўлидаги саёҳатингиз шу ердан бошланади.',
    'onboarding_access_account': 'Ҳисобингизга киринг',
    'onboarding_start_journey': 'Ўқув саёҳатингизни бошланг',
    'welcome_to': 'LabProof Academy га хуш келибсиз',
    'admin_login_subtitle': 'LabProof Academy админ панелига кириш',
    'confirm_password': 'Паролни тасдиқланг',
    'passwords_not_match': 'Пароллар бир хил эмас.',
    'reset_success':
        'Парол янгиланди. Энди янги парол билан киришингиз мумкин.',
    'full_name_required': 'Исм фамилияни киритинг.',
    'phone_invalid': 'Телефон рақам +998 дан кейин 9 та рақам бўлиши керак.',
    'password_required': 'Парол киритинг.',
    'password_min': 'Парол камида 6 та белги бўлиши керак.',
    'login': 'Кириш',
    'register': 'Рўйхатдан ўтиш',
    'verify': 'Тасдиқлаш',
    'get_code': 'Кодни олиш',
    'open_bot_again': 'Telegram ботни қайта очиш',
    'code': 'Telegram коди',
    'code_hint': 'Бот берган кодни киритинг',
    'telegram_hint':
        'Telegram бот аввал исм фамилияни текширади, кейин рақамни тугма орқали қабул қилади.',
    'telegram_opened':
        'Telegram очилди. Ботдаги “📞 Рақамни юбориш” тугмасини босинг, кейин кодни шу ерга киритинг.',
    'already': 'Аввал рўйхатдан ўтганмисиз?',
    'new': 'Янги фойдаланувчимисиз?',
    'student': 'Студент',
    'admin': 'Админ',
    'home': 'Бош саҳифа',
    'modules': 'Модуллар',
    'results': 'Натижалар',
    'progress': 'Прогресс',
    'profile': 'Профил',
    'hello': 'Салом',
    'today': 'Бугун ўқиш жараёнини давом эттиринг.',
    'continue': 'Давом этиш',
    'continue_learning': 'Ўқишни давом эттириш',
    'settings': 'Созламалар',
    'language': 'Тил',
    'language_picker_hint': 'Илова тилини қулай кўринишда танланг.',
    'dark_mode': 'Қоронғи режим',
    'logout': 'Чиқиш',
    'profile_subtitle': 'Шахсий маълумотлар, тил ва билдиришнома бошқаруви',
    'edit_profile': 'Профилни таҳрирлаш',
    'phone_not_set': 'Телефон рақам йўқ',
    'address_not_set': 'Манзил киритилмаган',
    'male': 'Эркак',
    'female': 'Аёл',
    'age_suffix': 'ёш',
    'studying_modules': 'Ўрганаётган модуллар',
    'completed_modules': 'Тугатилган модуллар',
    'overall_score': 'Умумий натижа',
    'notifications': 'Билдиришномалар',
    'notifications_enabled_hint': 'Ёқилган, янги эълонлар келади',
    'notifications_disabled_hint': 'Ўчиқ, хабарлар оқими тўхтатилган',
    'contact_admin': 'LabProof Academy Ёрдам',
    'contact_admin_subtitle': 'Савол, муаммо ёки таклиф юборинг',
    'support_subject': 'Хабар мавзуси',
    'support_message': 'Хабар матни',
    'support_message_hint': 'Муаммо ёки саволингизни қисқача ёзинг...',
    'fill_subject_message': 'Мавзу ва хабар матнини тўлдиринг.',
    'send_message': 'Хабар юбориш',
    'message_sent': 'Хабарингиз админга юборилди.',
    'dark_mode_enabled': 'Қоронғи кўриниш фаоллашган',
    'light_mode_enabled': 'Ёруғ кўриниш ишлатилмоқда',
    'check_updates': 'Янгиланишни текшириш',
    'check_updates_subtitle': 'Сўнгги релиз ва APK янгиланишини текшириш',
    'close_session': 'Жорий сессияни ёпиш',
    'version_label': 'Версия',
    'notifications_title': 'Билдиришномалар',
    'new_messages_count_suffix': 'та янги хабар',
    'notifications_disabled_profile':
        'Билдиришномалар профилдан ўчириб қўйилган',
    'mark_all_read': 'Барчаси ўқилди',
    'notifications_empty_title': 'Хабарлар ҳали йўқ',
    'notifications_empty_message':
        'Админ панелдан юборилган янгилик ва эълонлар шу ерда кўринади.',
    'notifications_off_title': 'Билдиришномалар ўчиқ',
    'notifications_off_message':
        'Профил саҳифасидаги свитч ёқилганда админ юборган янгиликлар шу ерга тушади.',
    'just_now': 'Ҳозиргина',
    'minutes_ago': 'дақиқа олдин',
    'hours_ago': 'соат олдин',
    'days_ago': 'кун олдин',
    'profile_edit_title': 'Профилни таҳрирлаш',
    'profile_edit_subtitle':
        'Шахсий маълумотлар, манзил ва профил расмини янгиланг.',
    'upload_profile_photo': 'Профил расмини юклаш',
    'first_name': 'Исм',
    'last_name': 'Фамилия',
    'gender': 'Жинс',
    'choose': 'Танланг',
    'region': 'Вилоят',
    'district': 'Туман',
    'mahalla': 'Маҳалла',
    'street_house': 'Кўча / уй',
    'saving': 'Сақланмоқда...',
    'save': 'Сақлаш',
    'choose_gender': 'Жинсни танланг',
    'choose_region': 'Вилоятни танланг',
    'choose_district': 'Туманни танланг',
    'select_region_first': 'Аввал вилоятни танланг.',
    'name_complete_error': 'Исм ва фамилияни тўлиқ киритинг.',
    'choose_gender_error': 'Жинсни танланг.',
    'choose_region_district_error': 'Вилоят ва туманни танланг.',
    'age_range_error': 'Ёш 10 дан 120 гача бўлиши керак.',
    'profile_updated': 'Профил маълумотлари янгиланди.',
    'active_modules': 'Фаол модуллар',
    'active_modules_subtitle': 'Очilgan ва давом этаётган блоклар',
    'score_average_subtitle': 'Quiz ва final тестлар ўртачаси',
    'completed_topics': 'Тугатилган мавзулар',
    'completed_topics_subtitle': 'Босқичма-босқич бажарилган дарслар',
    'certificates_subtitle': 'Якунланган модуллардан берилади',
    'average_result': 'Ўртача натижа',
    'evaluated_topics': 'Баҳоланган мавзулар',
    'notifications_tooltip': 'Билдиришномалар',
    'modules_subtitle': 'Модуллар кетма-кет очилади ва прогресс сақланади',
    'open': 'Очиқ',
    'locked': 'Ёпиқ',
    'topics': 'Мавзулар',
    'pass_rule': '70% ўтиш шарти',
    'final_exam': 'Модул якуний тести',
    'pdf_lesson': '1. PDF / Матн дарси',
    'video_lesson': '2. Видео дарс',
    'topic_quiz': '3. Мавзу тести',
    'finish_reading': 'Ўқишни тугатдим',
    'finish_video': 'Видеони тугатдим',
    'question': 'Савол',
    'previous': 'Олдинги',
    'next': 'Кейинги',
    'submit': 'Топшириш',
    'great': 'Ажойиб!',
    'topic_done': 'мавзусини тугатдингиз.',
    'back_topics': 'Мавзулар рўйхатига қайтиш',
    'start_test': 'Тестни бошлаш',
    'see_result': 'Натижани кўриш',
    'passed': 'Ўтдингиз!',
    'failed': 'Ўта олмадингиз',
    'next_module': 'Кейинги модул очилди',
    'review_retake': 'Дарсларни қайта кўриб, тестни қайта топширинг',
    'restudy': 'Қайта ўқиш',
    'go_module_2': '2-модулга ўтиш',
    'analytics': 'Тест таҳлиллари',
    'certificate': 'Сертификат',
    'achievements': 'Ютуқлар',
    'description': 'Тавсиф',
    'main_formula': 'Асосий формула',
    'video_not_open': 'Видеони очиб бўлмади.',
    'playback_speed': 'Ижро тезлиги',
    'open_external_video': 'Ташқи видеони очиш',
    'send_question': 'Савол юбориш',
    'join': 'Қўшилиш',
    'send_text_or_attachment': 'Ҳеч бўлмаса матн ёки бириктирма юборинг.',
    'stop': 'Тўхтатиш',
    'video_not_set': 'Бу мавзу учун видео ҳавола ҳали белгиланмаган.',
    'video_external_hint': 'Видео ҳавола орқали очилади. YouTube ҳаволаси бўлса, video ilova ichida кўрсатилади.',
    'video_inapp_hint': 'YouTube видео илова ichida кўрсатилмоқда.',
  },
};
